<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/berita', function () {
    return view('berita');
});

Route::get('/jadwal', function () {
    return view('jadwal');
});

Route::get('/peta-venue', function () {
    return view('venue');
});

Route::get('/fasilitas', function () {
    $facilities = [
        ['nama' => 'Zest Hotel Bogor', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Pajajaran No. 27, Babakan, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '1.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Zest%20Hotel%20Bogor%20Jl.%20Pajajaran%20No.%2027%2C%20Babakan%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'The Mirah Hotel Bogor', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Pangrango No. 9A, Babakan, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=The%20Mirah%20Hotel%20Bogor%20Jl.%20Pangrango%20No.%209A%2C%20Babakan%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Salak Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Jend. Sudirman No. 8, Sempur, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '1.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Salak%20Bogor%20Jl.%20Jend.%20Sudirman%20No.%208%2C%20Sempur%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS PMI Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Pajajaran No. 80, Baranangsiang, Kec. Bogor Timur, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '2.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20PMI%20Bogor%20Jl.%20Pajajaran%20No.%2080%2C%20Baranangsiang%2C%20Kec.%20Bogor%20Timur%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Juanda', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Ir. H. Juanda No. 30, Babakan, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '2.0 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Juanda%20Jl.%20Ir.%20H.%20Juanda%20No.%2030%2C%20Babakan%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Bogor Tengah', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Sawojajar No. 38, Pabaton, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '1.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Bogor%20Tengah%20Jl.%20Sawojajar%20No.%2038%2C%20Pabaton%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polresta Bogor Kota (Mako Muslihat)', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Kapten Muslihat No. 18, Paledang, Kec. Bogor Tengah, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '2.3 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polresta%20Bogor%20Kota%20%28Mako%20Muslihat%29%20Jl.%20Kapten%20Muslihat%20No.%2018%2C%20Paledang%2C%20Kec.%20Bogor%20Tengah%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Rumah Makan Ampera Pemuda', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Pemuda No. 27, Tanah Sareal, Kec. Tanah Sereal, Kota Bogor', 'venue' => 'GOR Pajajaran / Stadion Pajajaran (Indoor A, Indoor B, Stadion)', 'jarak' => '300 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Rumah%20Makan%20Ampera%20Jl.%20Pemuda%20No.%2027%20Tanah%20Sareal%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'ASTON Bogor Hotel & Resort', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Mulyaharja, Kec. Bogor Selatan, Kota Bogor', 'venue' => 'Green Forest Hotel', 'jarak' => '1.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=ASTON%20Bogor%20Hotel%20%26%20Resort%20Mulyaharja%2C%20Kec.%20Bogor%20Selatan%2C%20Kota%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Padodi Hotel', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Soemanta Diredja No. 10, Pamoyanan, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Padodi%20Hotel%20Jl.%20Soemanta%20Diredja%20No.%2010%2C%20Pamoyanan%2C%20Kec.%20Bogor%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Melania Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Pahlawan No. 91, Bondongan, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '2.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Melania%20Bogor%20Jl.%20Pahlawan%20No.%2091%2C%20Bondongan%2C%20Kec.%20Bogor%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Pahlawan', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Pahlawan No. 40, Batutulis, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '2.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Pahlawan%20Jl.%20Pahlawan%20No.%2040%2C%20Batutulis%2C%20Kec.%20Bogor%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Cipaku', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Rangga Gading, Cipaku, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '2.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Cipaku%20Jl.%20Rangga%20Gading%2C%20Cipaku%2C%20Kec.%20Bogor%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Bogor Selatan', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Layung Sari No. 1, Empang, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '2.6 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Bogor%20Selatan%20Jl.%20Layung%20Sari%20No.%201%2C%20Empang%2C%20Kec.%20Bogor%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Resto Kampoeng Konsep', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Soemanta Diredja No. 28, Pamoyanan, Kec. Bogor Selatan', 'venue' => 'Green Forest Hotel', 'jarak' => '400 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Resto%20Kampoeng%20Konsep%20Pamoyanan%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'IPB Hotel & Convention Centre', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Botani Square, Jl. Pajajaran, Baranangsiang', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '2.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=IPB%20Hotel%20%26%20Convention%20Centre%20Botani%20Square%2C%20Jl.%20Pajajaran%2C%20Baranangsiang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS PMI Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Pajajaran No. 80, Baranangsiang, Kec. Bogor Timur', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '2.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20PMI%20Bogor%20Jl.%20Pajajaran%20No.%2080%2C%20Baranangsiang%2C%20Kec.%20Bogor%20Timur', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Pajajaran', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Pajajaran No. 35, Babakan, Kec. Bogor Tengah', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Pajajaran%20Jl.%20Pajajaran%20No.%2035%2C%20Babakan%2C%20Kec.%20Bogor%20Tengah', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Bogor Utara', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Tegal Gundil, Kec. Bogor Utara', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '1.9 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Bogor%20Utara%20Jl.%20Tegal%20Gundil%2C%20Kec.%20Bogor%20Utara', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Bogor Utara', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Pajajaran No. 200, Cibuluh, Kec. Bogor Utara', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '2.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Bogor%20Utara%20Jl.%20Pajajaran%20No.%20200%2C%20Cibuluh%2C%20Kec.%20Bogor%20Utara', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Toko Adelways (Kantin IPB Cilibende)', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Cilibende, Babakan, Kec. Bogor Tengah', 'venue' => 'Gymnasium Sekolah Vokasi IPB', 'jarak' => '250 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Toko%20Adelways%20Jl.%20Cilibende%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'WHIZ Prime Hotel Bogor Yasmin', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. KH. R. Abdullah Bin Nuh No. 33, Curugmekar', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '600 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=WHIZ%20Prime%20Hotel%20Bogor%20Yasmin%20Jl.%20KH.%20R.%20Abdullah%20Bin%20Nuh%20No.%2033%2C%20Curugmekar', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Swiss-Belcourt Bogor', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. KH. R. Abdullah Bin Nuh No. 27, Bukit Cimanggu City', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '1.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Swiss-Belcourt%20Bogor%20Jl.%20KH.%20R.%20Abdullah%20Bin%20Nuh%20No.%2027%2C%20Bukit%20Cimanggu%20City', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Hermina Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. KH. R. Abdullah Bin Nuh No. E2, Hermina Grand Yasmin', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '900 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Hermina%20Bogor%20Jl.%20KH.%20R.%20Abdullah%20Bin%20Nuh%20No.%20E2%2C%20Hermina%20Grand%20Yasmin', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Islam Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Perdana No. 22, Budi Agung, Tanahsareal', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '2.0 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Islam%20Bogor%20Jl.%20Perdana%20No.%2022%2C%20Budi%20Agung%2C%20Tanahsareal', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Yasmin', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Ruko Taman Yasmin Sektor VI No. 108, Curugmekar', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '500 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Yasmin%20Ruko%20Taman%20Yasmin%20Sektor%20VI%20No.%20108%2C%20Curugmekar', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Gang Kelor', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raya Curug No. 12, Curugmekar, Kec. Bogor Barat', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '1.4 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Gang%20Kelor%20Jl.%20Raya%20Curug%20No.%2012%2C%20Curugmekar%2C%20Kec.%20Bogor%20Barat', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Tanah Sareal', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Seremped, Kedung Badak, Kec. Tanah Sareal', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '2.4 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Tanah%20Sareal%20Jl.%20Seremped%2C%20Kedung%20Badak%2C%20Kec.%20Tanah%20Sareal', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Rumah Makan Ampera Yasmin', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. KH. R. Abdullah Bin Nuh No. 37, Curugmekar', 'venue' => 'GOR Yasmin Bulutangkis', 'jarak' => '350 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Rumah%20Makan%20Ampera%20Yasmin%20Jl.%20KH.%20R.%20Abdullah%20Bin%20Nuh%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Salak Sunset Hotel', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Raya Kemang Parung No. 12, Kemang', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '2.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Salak%20Sunset%20Hotel%20Jl.%20Raya%20Kemang%20Parung%20No.%2012%2C%20Kemang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Sentosa Bogor', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Raya Kemang No. 18, Kemang, Kab. Bogor', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '1.3 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Sentosa%20Bogor%20Jl.%20Raya%20Kemang%20No.%2018%2C%20Kemang%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Kemang', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Raya Parung-Bogor, Kemang, Kab. Bogor', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '800 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Kemang%20Jl.%20Raya%20Parung-Bogor%2C%20Kemang%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Kemang', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raya Kemang No. 5, Kemang, Kab. Bogor', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '1.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Kemang%20Jl.%20Raya%20Kemang%20No.%205%2C%20Kemang%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Kemang', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Raya Kemang Parung No. 10, Kemang, Kab. Bogor', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Kemang%20Jl.%20Raya%20Kemang%20Parung%20No.%2010%2C%20Kemang%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RM Ayam Goreng Bakar Sayati', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Raya Parung - Bogor, Semplak Barat, Kemang', 'venue' => 'PPSDMAP Kemenhub Kemang Kab-Bogor', 'jarak' => '450 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Ayam%20Goreng%20Bakar%20Sayati%20Kemang%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Lorin Sentul Hotel', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Kawasan Sirkuit Sentul Internasional, Babakan Madang', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '1.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Lorin%20Sentul%20Hotel%20Kawasan%20Sirkuit%20Sentul%20Internasional%2C%20Babakan%20Madang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Harris Hotel Sentul City', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Jend. Sudirman, Sentul City, Babakan Madang', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '2.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Harris%20Hotel%20Sentul%20City%20Jl.%20Jend.%20Sudirman%2C%20Sentul%20City%2C%20Babakan%20Madang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS EMC Sentul', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. MH. Thamrin No. 57, Sentul City, Babakan Madang', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '2.7 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20EMC%20Sentul%20Jl.%20MH.%20Thamrin%20No.%2057%2C%20Sentul%20City%2C%20Babakan%20Madang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Sentul City', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Ruko Plaza Niaga 1, Sentul City', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '2.3 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Sentul%20City%20Ruko%20Plaza%20Niaga%201%2C%20Sentul%20City', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Babakan Madang', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raya Sentul No. 1, Babakan Madang', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '2.0 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Babakan%20Madang%20Jl.%20Raya%20Sentul%20No.%201%2C%20Babakan%20Madang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Babakan Madang', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Raya Babakan Madang No. 8, Kab. Bogor', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '2.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Babakan%20Madang%20Jl.%20Raya%20Babakan%20Madang%20No.%208%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Restoran Lorin Sentul', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Kawasan Sirkuit Sentul Internasional, Babakan Madang', 'venue' => 'Padepokan Voli Sentul', 'jarak' => '1.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Restoran%20Lorin%20Sentul%20Hotel%20Babakan%20Madang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Bobocabin Gunung Mas', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Gunung Mas, Jl. Raya Puncak Gadog No. KM 87, Cisarua', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '300 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Bobocabin%20Gunung%20Mas%20Gunung%20Mas%2C%20Jl.%20Raya%20Puncak%20Gadog%20No.%20KM%2087%2C%20Cisarua', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Grand Diara Hotel Puncak', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Raya Puncak - Gadog KM 77, Cisarua', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '2.9 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Grand%20Diara%20Hotel%20Puncak%20Jl.%20Raya%20Puncak%20-%20Gadog%20KM%2077%2C%20Cisarua', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RSPG Cisarua (RS Paru Dr. M. Goenawan)', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Raya Puncak No. KM 83, Cisarua, Kab. Bogor', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '1.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RSPG%20Cisarua%20%28RS%20Paru%20Dr.%20M.%20Goenawan%29%20Jl.%20Raya%20Puncak%20No.%20KM%2083%2C%20Cisarua%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Cisarua', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Raya Puncak No. 412, Cisarua, Kab. Bogor', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Cisarua%20Jl.%20Raya%20Puncak%20No.%20412%2C%20Cisarua%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Cisarua', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raya Puncak No. KM 81, Cisarua, Kab. Bogor', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '2.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Cisarua%20Jl.%20Raya%20Puncak%20No.%20KM%2081%2C%20Cisarua%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Cisarua', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Raya Puncak KM 82, Cisarua, Kab. Bogor', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '2.3 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Cisarua%20Jl.%20Raya%20Puncak%20KM%2082%2C%20Cisarua%2C%20Kab.%20Bogor', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Resto Agrowisata Gunung Mas', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Kawasan Agrowisata Gunung Mas, Tugu Selatan, Cisarua', 'venue' => 'Gunung Mas (Cisarua)', 'jarak' => '200 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Resto%20Agrowisata%20Gunung%20Mas%20Cisarua', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Hotel Trikarya Cimahi', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Raya Cisangkan No. 88, Padasuka, Cimahi Tengah', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '800 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Hotel%20Trikarya%20Cimahi%20Jl.%20Raya%20Cisangkan%20No.%2088%2C%20Padasuka%2C%20Cimahi%20Tengah', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Dustira Cimahi', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Dr. Dustira No. 1, Baros, Cimahi Tengah', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '2.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Dustira%20Cimahi%20Jl.%20Dr.%20Dustira%20No.%201%2C%20Baros%2C%20Cimahi%20Tengah', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Cisangkan', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Raya Cisangkan No. 12, Padasuka, Cimahi Tengah', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '400 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Cisangkan%20Jl.%20Raya%20Cisangkan%20No.%2012%2C%20Padasuka%2C%20Cimahi%20Tengah', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Cimahi Tengah', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raden Demang Hardjakusumah No. 1, Cimahi', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '1.6 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Cimahi%20Tengah%20Jl.%20Raden%20Demang%20Hardjakusumah%20No.%201%2C%20Cimahi', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polres Cimahi', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Raya Cibeureum No. 1, Cimahi Selatan', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '2.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polres%20Cimahi%20Jl.%20Raya%20Cibeureum%20No.%201%2C%20Cimahi%20Selatan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RM Ampera Cisangkan', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Raya Barat No. 805, Padasuka, Cimahi Tengah', 'venue' => 'Lapangan Tembak Cisangkan', 'jarak' => '350 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RM%20Ampera%20Cisangkan%20Jl.%20Raya%20Barat%20No.%20805%20Cimahi', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Grand Cordela Hotel Bandung', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Soekarno-Hatta No. 791, Cisaranten Endah, Arcamanik', 'venue' => 'Arcamanik', 'jarak' => '2.4 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Grand%20Cordela%20Hotel%20Bandung%20Jl.%20Soekarno-Hatta%20No.%20791%2C%20Cisaranten%20Endah%2C%20Arcamanik', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Hermina Arcamanik', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. A.H. Nasution No. 50, Antapani, Bandung', 'venue' => 'Arcamanik', 'jarak' => '1.7 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Hermina%20Arcamanik%20Jl.%20A.H.%20Nasution%20No.%2050%2C%20Antapani%2C%20Bandung', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Arcamanik', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. Arcamanik Endah No. 42, Sukamiskin, Arcamanik', 'venue' => 'Arcamanik', 'jarak' => '600 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Arcamanik%20Jl.%20Arcamanik%20Endah%20No.%2042%2C%20Sukamiskin%2C%20Arcamanik', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Arcamanik', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Cisaranten Kulon No. 4, Arcamanik, Bandung', 'venue' => 'Arcamanik', 'jarak' => '1.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Arcamanik%20Jl.%20Cisaranten%20Kulon%20No.%204%2C%20Arcamanik%2C%20Bandung', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Arcamanik', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Pacuan Kuda No. 54, Sukamiskin, Arcamanik', 'venue' => 'Arcamanik', 'jarak' => '800 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Arcamanik%20Jl.%20Pacuan%20Kuda%20No.%2054%2C%20Sukamiskin%2C%20Arcamanik', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RM Khas Sunda Cibiuk Arcamanik', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Soekarno Hatta No. 741, Cisaranten Endah, Arcamanik', 'venue' => 'Arcamanik', 'jarak' => '1.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RM%20Khas%20Sunda%20Cibiuk%20Soekarno%20Hatta%20Arcamanik%20Bandung', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Mason Pine Hotel', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. Raya Kotabaru Parahyangan, Cipeundeuy, Padalarang', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '500 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Mason%20Pine%20Hotel%20Jl.%20Raya%20Kotabaru%20Parahyangan%2C%20Cipeundeuy%2C%20Padalarang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RS Cahya Kawaluyan', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Raya Parahyangan KM 1.5, Padalarang, Bandung Barat', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '1.2 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RS%20Cahya%20Kawaluyan%20Jl.%20Raya%20Parahyangan%20KM%201.5%2C%20Padalarang%2C%20Bandung%20Barat', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma KBP', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Ruko Bumi Simpang, Kota Baru Parahyangan', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '800 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20KBP%20Ruko%20Bumi%20Simpang%2C%20Kota%20Baru%20Parahyangan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Padalarang', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. Raya Padalarang No. 470, Bandung Barat', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '2.8 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Puskesmas%20Padalarang%20Jl.%20Raya%20Padalarang%20No.%20470%2C%20Bandung%20Barat', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polsek Padalarang', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. Raya Padalarang No. 501, Bandung Barat', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '2.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polsek%20Padalarang%20Jl.%20Raya%20Padalarang%20No.%20501%2C%20Bandung%20Barat', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Bumi Aki Kota Baru Parahyangan', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. Parahyangan Raya No. 1, Kota Baru Parahyangan', 'venue' => 'Kota Baru Parahyangan', 'jarak' => '600 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Bumi%20Aki%20Kota%20Baru%20Parahyangan%20Padalarang', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Fitra Hotel Majalengka', 'tipe' => 'hotel', 'tipe_label' => 'Hotel', 'alamat' => 'Jl. KH. Abdul Halim No. 88, Majalengka Kulon', 'venue' => 'Majalengka', 'jarak' => '1.1 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Fitra%20Hotel%20Majalengka%20Jl.%20KH.%20Abdul%20Halim%20No.%2088%2C%20Majalengka%20Kulon', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RSUD Majalengka', 'tipe' => 'rs', 'tipe_label' => 'Rumah Sakit', 'alamat' => 'Jl. Kesehatan No. 77, Majalengka Wetan', 'venue' => 'Majalengka', 'jarak' => '1.5 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=RSUD%20Majalengka%20Jl.%20Kesehatan%20No.%2077%2C%20Majalengka%20Wetan', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Apotek Kimia Farma Majalengka', 'tipe' => 'apotek', 'tipe_label' => 'Apotek', 'alamat' => 'Jl. KH. Abdul Halim No. 120, Majalengka', 'venue' => 'Majalengka', 'jarak' => '900 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Apotek%20Kimia%20Farma%20Majalengka%20Jl.%20KH.%20Abdul%20Halim%20No.%20120%2C%20Majalengka', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Puskesmas Majalengka', 'tipe' => 'puskesmas', 'tipe_label' => 'Puskesmas', 'alamat' => 'Jl. KH. Abdul Halim No. 200, Majalengka', 'venue' => 'Majalengka', 'jarak' => '1.3 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=%20%20%20Jl.%20KH.%20Abdul%20Halim%20No.%20200%2C%20Majalengka', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'Polres Majalengka', 'tipe' => 'polsek', 'tipe_label' => 'Polres / Polsek', 'alamat' => 'Jl. KH. Abdul Halim No. 512, Majalengka', 'venue' => 'Majalengka', 'jarak' => '2.0 km', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Polres%20Majalengka%20Jl.%20KH.%20Abdul%20Halim%20No.%20512%2C%20Majalengka', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
        ['nama' => 'RM Khas Sunda Saung Balong', 'tipe' => 'restoran', 'tipe_label' => 'Restoran', 'alamat' => 'Jl. KH. Abdul Halim No. 160, Majalengka Wetan', 'venue' => 'Majalengka', 'jarak' => '700 m', 'gmaps' => 'https://www.google.com/maps/search/?api=1&query=Saung%20Balong%20Jl.%20KH.%20Abdul%20Halim%20Majalengka', 'telepon' => '-', 'layanan' => '-', 'website' => '', 'image' => ''],
    ];

    // Count stats
    $stats = [
        'total' => count($facilities),
        'rs' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'rs')),
        'puskesmas' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'puskesmas')),
        'apotek' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'apotek')),
        'hotel' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'hotel')),
        'polsek' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'polsek')),
        'restoran' => count(array_filter($facilities, fn($f) => $f['tipe'] === 'restoran')),
    ];

    return view('fasilitas', compact('facilities', 'stats'));
});

Route::get('/galeri', function () {
    return view('galeri');
});

Route::get('/kebijakan-privasi', function () {
    return view('privasi');
});
